"""Step 8: Seed PostgreSQL with pipeline outputs.

Reads the feature matrix (with role labels) and qualified players,
then inserts into the players, teams, player_seasons, player_features,
and player_vectors tables via SQLAlchemy.

Uses pickle to load the sklearn StandardScaler generated by our own
build_index pipeline step — not from any external source.
"""

from __future__ import annotations

import logging
import pickle  # noqa: S403 — loading our own sklearn scaler
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.orm import Session

_PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from app.config import settings
from app.database import Base
from app.models import Player, PlayerFeature, PlayerSeason, PlayerVector, Team
from app.utils.constants import FEATURE_NAMES

logger = logging.getLogger(__name__)

FEATURES_DIR = Path(__file__).resolve().parents[1].parent / "data" / "features"
MODELS_DIR = Path(__file__).resolve().parents[1].parent / "data" / "models"


def seed_db(drop_existing: bool = False) -> None:
    """Insert all pipeline data into PostgreSQL."""
    engine = create_engine(settings.database_url_sync, echo=False)

    if drop_existing:
        Base.metadata.drop_all(engine)
        logger.info("Dropped all existing tables")

    Base.metadata.create_all(engine)
    logger.info("Created tables")

    feature_path = FEATURES_DIR / "feature_matrix.parquet"
    if not feature_path.exists():
        logger.error("Feature matrix not found — run the pipeline first")
        return

    df = pd.read_parquet(feature_path)
    logger.info("Loaded feature matrix: %d players", len(df))

    # Reconstruct normalised vectors from FAISS
    vectors: dict[int, list[float]] = {}
    try:
        import faiss
        index_path = MODELS_DIR / "faiss_index.bin"
        map_path = MODELS_DIR / "player_id_map.npy"
        if index_path.exists() and map_path.exists():
            index = faiss.read_index(str(index_path))
            player_ids_arr = np.load(str(map_path))
            all_vecs = np.zeros((index.ntotal, index.d), dtype=np.float32)
            for i in range(index.ntotal):
                index.reconstruct(i, all_vecs[i])
            for i, pid in enumerate(player_ids_arr):
                vectors[int(pid)] = all_vecs[i].tolist()
            logger.info("Loaded %d vectors from FAISS index", len(vectors))
    except Exception as exc:
        logger.warning("Could not load FAISS vectors: %s", exc)

    with Session(engine) as session:
        # Clear in dependency order
        for tbl in ["player_vectors", "player_features", "shortlists",
                     "player_seasons", "players", "teams", "users"]:
            try:
                session.execute(text(f"DELETE FROM {tbl}"))
            except Exception:
                pass
        session.commit()
        logger.info("Cleared existing data")

        # Teams
        team_lookup: dict[str, int] = {}
        team_rows = df[["team_name", "league"]].drop_duplicates()
        for i, (_, row) in enumerate(team_rows.iterrows(), start=1):
            session.add(Team(
                team_id=i,
                team_name=row["team_name"],
                league=row["league"],
                season="2015/2016",
            ))
            team_lookup[row["team_name"]] = i
        session.flush()
        logger.info("Inserted %d teams", len(team_lookup))

        # Players + PlayerSeasons
        inserted_players: set[int] = set()
        ps_id_map: dict[int, int] = {}

        for ps_id, (_, row) in enumerate(df.iterrows(), start=1):
            pid = int(row["player_id"])

            if pid not in inserted_players:
                session.add(Player(
                    player_id=pid,
                    player_name=row.get("player_name", ""),
                    nationality=row.get("nationality") if pd.notna(row.get("nationality")) else None,
                    primary_position=row.get("primary_position"),
                ))
                inserted_players.add(pid)

            age_val = int(row["age"]) if pd.notna(row.get("age")) else 25
            session.add(PlayerSeason(
                id=ps_id,
                player_id=pid,
                team_id=team_lookup.get(row.get("team_name", "")),
                season="2015/2016",
                age=age_val,
                minutes_played=int(row.get("total_minutes", 0)),
                matches_played=int(row.get("matches_played", 0)),
                role_label=row.get("role_label"),
                role_confidence=float(row["role_confidence"]) if pd.notna(row.get("role_confidence")) else None,
            ))
            ps_id_map[pid] = ps_id
        session.flush()
        logger.info("Inserted %d players, %d player_seasons", len(inserted_players), len(ps_id_map))

        # Features
        for _, row in df.iterrows():
            pid = int(row["player_id"])
            session.add(PlayerFeature(
                player_season_id=ps_id_map[pid],
                **{fn: float(row[fn]) for fn in FEATURE_NAMES},
            ))

        # Vectors
        vec_count = 0
        for pid, ps_id in ps_id_map.items():
            vec = vectors.get(pid)
            if vec:
                session.add(PlayerVector(player_season_id=ps_id, vector=vec))
                vec_count += 1

        session.commit()
        logger.info("Inserted %d features, %d vectors", len(ps_id_map), vec_count)

    # Verify
    with Session(engine) as session:
        for tbl in ["players", "teams", "player_seasons", "player_features", "player_vectors"]:
            count = session.execute(text(f"SELECT COUNT(*) FROM {tbl}")).scalar()
            logger.info("  %s: %d rows", tbl, count)


def run() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
    )
    logger.info("=== Step 8: Database seeding ===")
    t0 = time.perf_counter()
    seed_db(drop_existing="--drop" in sys.argv)
    logger.info("Seeding complete in %.1fs", time.perf_counter() - t0)


if __name__ == "__main__":
    run()
