"""Similarity search engine backed by FAISS.

Loads the pre-built index, scaler, and player map at startup.
Supports role-filtered search, custom dimension weights, and
post-filtering by league/age/minutes.

Pickle is required here to deserialise sklearn's StandardScaler
which was generated by our own build_index pipeline step.
"""

from __future__ import annotations

import logging
import pickle  # noqa: S403 — deserialising our own sklearn scaler
from pathlib import Path

import faiss
import numpy as np
from sklearn.preprocessing import normalize

from app.config import settings
from app.utils.constants import (
    DIMENSION_GROUPS,
    DIMENSION_KEY_MAP,
    FEATURE_NAMES,
    INCOMPATIBLE_ROLE_PAIRS,
    ROLE_DIMENSION_WEIGHTS,
)

logger = logging.getLogger(__name__)

# Singleton — loaded once at startup via load_index()
_index: faiss.IndexFlatIP | None = None
_scaler = None
_player_ids: np.ndarray | None = None


def load_index() -> None:
    """Load FAISS index, scaler, and player map from disk."""
    global _index, _scaler, _player_ids

    # Resolve paths relative to project root (one level above backend/)
    project_root = Path(__file__).resolve().parents[3]
    index_path = project_root / settings.faiss_index_path
    scaler_path = project_root / settings.scaler_path
    map_path = project_root / settings.player_map_path

    if not index_path.exists():
        logger.warning("FAISS index not found at %s", index_path)
        return

    _index = faiss.read_index(str(index_path))
    logger.info("FAISS index loaded: %d vectors", _index.ntotal)

    with open(scaler_path, "rb") as f:
        _scaler = pickle.load(f)  # noqa: S301

    _player_ids = np.load(str(map_path))
    logger.info("Player map loaded: %d IDs", len(_player_ids))


def _get_player_index(player_id: int) -> int | None:
    """Map player_id → row position in the FAISS index."""
    if _player_ids is None:
        return None
    matches = np.where(_player_ids == player_id)[0]
    return int(matches[0]) if len(matches) > 0 else None


def _apply_weights(vector: np.ndarray, weights: dict[str, float]) -> np.ndarray:
    """Scale feature dimensions by weights, then re-L2-normalise."""
    weighted = vector.copy()
    for short_key, weight in weights.items():
        dim_name = DIMENSION_KEY_MAP.get(short_key, short_key)
        indices = DIMENSION_GROUPS.get(dim_name)
        if indices:
            weighted[indices] *= weight

    norm = np.linalg.norm(weighted)
    if norm > 0:
        weighted /= norm
    return weighted


def search_similar(
    player_id: int,
    k: int = 10,
    role_filter: bool = True,
    feature_weights: dict[str, float] | None = None,
    player_metadata: dict[int, dict] | None = None,
    league_filter: str | None = None,
    age_min: int | None = None,
    age_max: int | None = None,
    min_minutes: int = 900,
) -> list[dict]:
    """Find the k most similar players to the query.

    Returns list of dicts with player_id, similarity_score, and metadata.
    """
    if _index is None or _scaler is None or _player_ids is None:
        raise RuntimeError("Index not loaded — call load_index() at startup")

    query_idx = _get_player_index(player_id)
    if query_idx is None:
        return []

    # Reconstruct the stored vector via the public FAISS API
    query_vec = np.zeros((1, _index.d), dtype=np.float32)
    _index.reconstruct(query_idx, query_vec[0])
    query_vec = query_vec[0].copy()

    # Resolve the query player's role once for filtering + weighting
    query_role: str | None = None
    if player_metadata:
        query_role = player_metadata.get(player_id, {}).get("role_label")

    # Weight dimensions — either custom or role defaults
    if feature_weights:
        query_vec = _apply_weights(query_vec, feature_weights)
    elif role_filter and query_role and query_role in ROLE_DIMENSION_WEIGHTS:
        query_vec = _apply_weights(query_vec, ROLE_DIMENSION_WEIGHTS[query_role])

    query_vec = query_vec.reshape(1, -1).astype(np.float32)

    # Over-fetch to allow for post-filter trimming
    buffer = k * 5
    D, I = _index.search(query_vec, min(buffer, _index.ntotal))

    results = []

    for score, idx in zip(D[0], I[0]):
        if idx < 0 or idx >= len(_player_ids):
            continue

        pid = int(_player_ids[idx])
        if pid == player_id:
            continue

        meta = player_metadata.get(pid, {}) if player_metadata else {}

        # Same-role constraint
        if role_filter and query_role and meta.get("role_label") != query_role:
            continue

        # Block incompatible pairings (§4)
        candidate_role = meta.get("role_label")
        if query_role and candidate_role:
            if frozenset({query_role, candidate_role}) in INCOMPATIBLE_ROLE_PAIRS:
                continue

        # League / age / minutes filters
        if league_filter and meta.get("league") != league_filter:
            continue
        if age_min is not None and meta.get("age", 0) < age_min:
            continue
        if age_max is not None and meta.get("age", 99) > age_max:
            continue
        if meta.get("minutes_played", 0) < min_minutes:
            continue

        results.append({
            "player_id": pid,
            "similarity_score": round(float(score), 4),
            **meta,
        })

        if len(results) >= k:
            break

    return results
